accessoryRarity = 1.0
corruptionEnabled = true

[caveChest]
chestRarity = 3
mimicChance = 15
minSurfaceY = 25
maxSurfaceY = 55
minCaveY = -55
maxCaveY = 25
deepCaveY = -30

[structures]
floatingIslandHeight = 180
